### ISSUE TITLE
OffsetArrays.jl package does not work in 0.3.12 and 0.4.1

### ISSUE THREAD

**Issue by tedwetherbee** [alsam/OffsetArrays.jl#1]
'''
Version 0.3.12 , using console
julia> Pkg.installed()
Dict{ASCIIString,VersionNumber} with 1 entry:
"OffsetArrays" => v"0.0.0-"
julia> using OffsetArrays
julia> y = OffsetArray(Float32,-1:1);
julia> y
NaN
NaN
0.0
julia> y[0] = 5.0
ERROR: arrayset not defined
 in setindex! at /home/juser/.julia/v0.3/OffsetArrays/src/OffsetArrays.jl:72
julia>

Version 0.3.12, using Ijulia
In: Pkg.installed()
Dict{ASCIIString,VersionNumber} with 1 entry:
  "OffsetArrays" => v"0.0.0-"
In: using OffsetArrays
In: y = OffsetArray(Float32, -1:1)
arraysize not defined

 in showarray at show.jl:1097
 in anonymous at replutil.jl:27
 in with_output_limit at ./show.jl:1136
 in writemime at replutil.jl:26
 in writemime at multimedia.jl:41
 in sprint at iostream.jl:229
 in display_dict at /opt/julia_packages/.julia/v0.3/IJulia/src/execute_request.jl:26
In:

Version 0.4.1, using ijulia
In: Pkg.installed()
Dict{ASCIIString,VersionNumber} with 1 entry:
  "OffsetArrays" => v"0.0.0-"
In: using OffsetArrays
LoadError: LoadError: UndefVarError: Range1 not defined
while loading /home/juser/.julia/v0.4/OffsetArrays/src/OffsetArrays.jl, in expression starting on line 8
while loading In[6], in expression starting on line 1

 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in require at ./loading.jl:243
In:
'''

**Comment by alsam** [comment]
Thanks a lot for the issue.
The issue has been fixed and will be closes after testing.

**Comment by alsam** [comment]
@tedwetherbee could you please confirm that the issue fixed and after that close it?

**Comment by tedwetherbee** [comment]
Please do close it.  I was just checking Julia out for possible use where
I've been using Fortran.

Ted

**Comment by alsam** [comment]
Great thanks, closing it. I'm tagging it  https://github.com/JuliaLang/METADATA.jl/pull/5417
Besides that @timholy made a new implementation for 0.5 [New implementation based on julia-0.5 infrastructure #2 ](https://github.com/alsam/OffsetArrays.jl/pull/2)
The new implementation will be available after finishing tagging.

**Comment by alsam** [comment]
I tagged the version that supports julia 0.3, 0.4 with `0.1.3`
Please use `Pkg.add("OffsetArrays")` instead of `Pkg.clone(...)` because the version that supports julia 03, 04 leaves in the separate branch called `pre-arraymageddon`
The new julia 0.5 implementation made by @timholy is pushed to `master` branch, but there is a showstopper to tag it properly, see https://github.com/JuliaLang/PkgDev.jl/issues/48 and https://github.com/alsam/OffsetArrays.jl/pull/2#issuecomment-227026432 for details.
You can enable it for julia 0.5 by `Pkg.clone("https://github.com/alsam/OffsetArrays.jl")`.
